- manifests/07_deployment.yaml
We don't use NFS CSI driver for Cinder, so we don't have to set this variable.
> Do not set NFS_DRIVER_IMAGE variable

- assets/controller.yaml
- assets/node.yaml
- pkg/generated/bindata.go
Mount the cacert in the `csi-driver` containers of the controller and
node pods.
Regenerated the bindata with: `make update-bindata`.
CSO takes care of synchronizing `openshift-config/cloud-provider-config`
configmap into the `openshift-cluster-csi-drivers/cloud-provider-config`
one.
Ref [OSASINFRA-2140](https://issues.redhat.com/browse/OSASINFRA-2140)
> Enable Cinder CSI to work with self-signed certificates

- assets/controller.yaml
- assets/node.yaml
- manifests/07_deployment.yaml
- pkg/generated/bindata.go
Because of this error the containers were running in best-effort QoS.
> Fix resources in deployment template

- assets/controller.yaml
- pkg/generated/bindata.go
According to the documentation Cinder CSI driver supports Topology feature[1].
This commit enables the feature for the external provisioner.
[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#topology
> Enable topology support

- assets/node.yaml
- pkg/generated/bindata.go
The `cinder-csi-driver-node` pods are supposed to run on every nodes.
This allows master to use PVCs too.
> Bug 1902546: Allow cinder-csi-driver-node pods to run everywhere

- OWNERS
To have OpenStack team coverage.
@Fedosin @mandre, PTAL.
Reusing an unrelated BZ to get it merged soon-ish.
> Bug 1902547: Add Mike and Martin to OWNERS

- pkg/operator/starter.go
The informer must be started to be actually usable. It was added in #21.
> Bug 1918140: Fix sync of config.openshift.io informer

- assets/controller.yaml
- pkg/generated/bindata.go
The snapshotter supports only `--metrics-address` to set up http endpoint for metrics. `--http-address` is silently ignored.
@openshift/storage
> Bug 1954003: Fix snapshotter metrics endpoint

- assets/volumesnapshotclass.yaml
- pkg/generated/bindata.go
- pkg/operator/starter.go
Now it's not possible to make volume snapshots right after installation, because there are no VolumeSnapshotClasses in the system.
This commit allows the operator to generate a default VolumeSnapshotClass along with the driver provisioning.
> Bug 1905849: create default VolumeSnapshotClass

- OWNERS
- assets/controller.yaml
- assets/node.yaml
https://bugzilla.redhat.com/show_bug.cgi?id=1989215
cc @openshift/storage
> Bug 1989215: [openstack-cinder-csi-driver-operator] csi-liveness-probe is not deployed

- .ci-operator.yaml
- Dockerfile
- pkg/dependencymagnet/dependencymagnet.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/5b89f5b601508a0bcc0399fd3f34b7aa2e86e90e/images/ose-openstack-cinder-csi-driver-operator.yml
Replaces #59
> Updating ose-openstack-cinder-csi-driver-operator images to be consistent with ART

- assets/controller.yaml
- assets/node.yaml
We have noticed that the current timeout values are not working against
certain clouds, like PSI, but potentially other customer clouds which
might be slower for some reasons (remote clouds, or large
infrastructures, etc).
This patch will relax the numbers by waiting 10s instead of 3s for the
check to finish, and instead of running it ever 10s, we'll run it every
30s (twice a minute) which should be enough for our needs.
> Bug 2027685: relax health probes against Cinder API

- assets/csidriver.yaml
- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/admissionregistration.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/generic.go
- vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/storage.go
- vendor/github.com/openshift/library-go/pkg/operator/staticresourcecontroller/static_resource_controller.go
- vendor/modules.txt
And set other CSIDriver fields. Since volumes of this CSI driver always support `fsGroup`, don't depend on Kubernetes heuristics (`ReadWriteOnceWithFSType`) and always apply it.
This updates library-go to https://github.com/openshift/library-go/pull/1324 to re-create driver's CSIDriver instance if the operator needs to change it.
It's somewhat related to https://bugzilla.redhat.com/show_bug.cgi?id=2058626, it makes sure the BZ never happens again.
cc @openshift/storage
> Set fsGroupPolicy in CSIDriver

- pkg/operator/cloudinfo.go
Not doing so would later lead to segfault, when we assume either
ci.ComputeZones or ci.VolumeZones have at least one element.
> Bug 2061732: Fail gracefully on failure to populate cloud info

- go.mod
- go.sum
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
- vendor/modules.txt
See the [Prometheus advisory](https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p)
**What this PR does / why we need it**:
This patch upgrades `github.com/prometheus/client_golang` to v1.11.1,
where the vulnerability has been fixed.
This commit is the result of running:
```
go get github.com/prometheus/client_golang \
&& go mod tidy && go mod vendor
```
**Notes for the reviewer**:
One handy way to check that the version of `client_go` used for compiling contains the security patch, is to check that the vendored code contains a `InstrumentRoundTripperCounter` method [accepting a variadic `options` argument](https://github.com/prometheus/client_golang/compare/v1.11.0...v1.11.1#diff-7871a83741d29b5f29e3c47d1c284f948c258a0c6fc18895f0c2d4204cc46054R63).
For …
> Bug 2067869: Address CVE-2022-21698

- go.mod
- go.sum
- vendor/golang.org/x/crypto/cryptobyte/asn1.go
- vendor/golang.org/x/crypto/cryptobyte/builder.go
- vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
- vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
- vendor/modules.txt
Upgrade golang.org/x/crypto to latest (pushed on Apr 11, 2022).
This commit is the result of running:
```
go get golang.org/x/crypto/ssh@latest \
&& go mod tidy && go mod vendor
```
See https://groups.google.com/g/golang-announce/c/-cp44ypCT5s/m/wmegxkLiAQAJ
**What this PR does / why we need it**:
Upgrades golang.org/x/crypto/ssh to latest, where the vulnerability has been fixed.
> Bug 2074292: Address CVE-2022-27191

- assets/controller.yaml
CVE-2016-2183
CVE-2016-6329
The default ciphers are not secure and are susceptible to a number of
different known vulnerabilities. This collection of ciphers should be
more secure and have no known vulnerabilities present.
Specific ciphers cribbed from https://github.com/openshift/cluster-machine-approver/commit/1f541e8a321ae57e1a8b1daf8c7890d96ae9e367
> Bug 2090662: SWEET32: Improve TLS configuration for Kube RBAC Proxy

- assets/controller.yaml
This fixes the remaining 3 kube-rbac-proxy sidecars.
CVE-2016-2183
CVE-2016-6329
The default ciphers are not secure and are susceptible to a number of
different known vulnerabilities. This collection of ciphers should be
more secure and have no known vulnerabilities present.
> Bug 2090662: SWEET32: Improve TLS configuration for Kube RBAC Proxy (cont)

- pkg/operator/starter.go
Ensure node service is updated if the credentials secret is changed.
> Bug OCPBUGS-2845: Add SecretHashAnnotation to node service

- pkg/operator/starter.go
This is an manual cherry-pick of https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/99.
Supersedes https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/102.
> [release-4.10] Bug OCPBUGS-4717: Add SecretHashAnnotation to node service

- pkg/operator/starter.go
RBAC rules should be created before their ServiceAccounts, so SCC admission has all of them present when validating a Pod + its ServiceAccount.
> OCPBUGS-16678: Fix SCC admission failure race during initial deployment

- pkg/controllers/config/cloudinfo.go
This can be a helpful breadcrumb when debugging services.
Note that the version information ldflags are populated by [build-machinery-go](https://github.com/openshift/build-machinery-go), which provides e.g. the `build` makefile target.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
> Configure User Agent

- pkg/operator/starter.go
- Adding WithSecretHashAnnotationHook() for openstack-cinder-csi-driver-controller ensures that new annotation is published in openstack-cinder-csi-driver-controller deployment. This, in turn, leads to controller pods restart.
> STOR-1436: Restart `openstack-cinder-csi-driver-controller` Pods if metrics-serving-cert changed

- README.md
- assets/controller.yaml
- pkg/controllers/config/cloudinfo.go
- pkg/controllers/config/configsync.go
- pkg/controllers/config/configsync_test.go
Currently, the topology feature is always enabled, regardless of any cloud-specific configuration. While topology awareness can be a good thing, it doesn't work so well in environments where e.g. there are multiple compute AZs but only a single storage AZ (e.g. non-HCI [1] deployments). We had previously relied on the `ignore_volume_az` flag to workaround this but as we've discovered, this doesn't do what we'd expect it to do [2].
Provide a mechanism for disabling topology functionality automatically based on the compute and storage AZs. In short, if the number and names of AZs are identical between the two services the it is assumed that the environment is a correctly-configured multi-AZ environment and topology-awareness should be *enabled*. If this is not the case, topology-awareness …
> STOR-1281: Make Cinder CSI Driver Topology feature configurable

- pkg/controllers/config/cloudinfo.go
The only requirement is that for every compute zone we have a matching volume zone with the same name. It's perfectly fine to have extra volume zones, as the scheduler won't provision volumes on them.
It is still possible for users to overwrite that default and set the `enable_topology` key to the desired value in the
`openshift-config/cloud-provider-config` config map.
> OCPBUGS-30951: Relax requirement to enable topology

- README.md
- assets/controller.yaml
- pkg/controllers/config/cloudinfo.go
- pkg/controllers/config/configsync.go
- pkg/controllers/config/configsync_test.go
This is manual backport of #127.
We include the contents of #110 to avoid merge conflicts. A backport of that PR is also proposed separately at #157 in case it is helpful to merge separately. The single commit here should disappear when that happens.
We also include the contents of #164 to fix a minor issue in the original version of this feature. This could be done later in a separate PR but it seems more sensible to include this now.
> OCPBUGS-34792: Make Cinder CSI Driver Topology feature configurable

- pkg/controllers/config/cloudinfo.go
Ensure that we have the same number or fewer compute AZs than volume AZs. Also better handle mismatches between the two.
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
Suggested-by: Daniel Kobras (@dkobras)
> OCPBUGS-34870: Correct out-of-bounds check

- README.md
We are in the process of migrating everything across to csi-operator. See [[1]] and [[2]] for more context.
[1]: https://github.com/openshift/csi-operator/pull/278
[2]: https://github.com/openshift/release/pull/56812
> OSASINFRA-3609: Mark the repository as obsolete
